php:
    image: php:8.0-apache
    container_name: php-container
    restart: always
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - /home/joaoribeiro/development/template-training/backend:/var/www/html
    links:
        - db
        - db:database
db:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    ports:
        - "3306:3306"
    volumes:
        -  /home/joaoribeiro/development/template-training/backend/database/db:/var/www/mysql
    environment:
        - MYSQL_USER=root
        - MYSQL_ROOT_PASSWORD=root
vue:
    container_name: vue-container
    image: node:12
    ports:
        - "8080:8080"
    volumes:
        - ./frontend:/srv/app
    working_dir: /srv/app
    command: 'npm run serve'


