version: "3.7"
services:
  php:
    build:
      args:
        user: joaoribeiro
        uid: 1000
      context: ./backend
      dockerfile: Dockerfile
    image: container
    container_name: php-container
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
       - ./backend:/var/www/html
    networks:
      - container
    links:
      - db
      - db:database
  db:
      image: mysql:latest
      container_name: mysql-container
      restart: always
      ports:
          - "3306:3306"
      volumes:
          -  ./backend/database/db:/var/www/mysql
      environment:
          - MYSQL_USER=root
          - MYSQL_ROOT_PASSWORD=root
      networks:
        - container
  vue:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      container_name: vue-container
      image: node:12
      ports:
          - "8080:8080"
      volumes:
          - ./frontend:/srv/app
      working_dir: /srv/app
      command: 'npm run serve'
      networks:
        - container
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8003:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - container

networks:
  container:
    driver: bridge

